### ISSUE TITLE
Only strings can be used as value radio buttons.

### ISSUE THREAD

**Issue by navyfox** [final-form/react-final-form#217]
Hi @erikras , thank you for your great library. I am running into some issues with radio buttons in particular.

### **Bug report**
I want to use a number as the value, but I do not checked the radio button. I clicked and the value was recorded, but the input did not respond.

### Sandbox Link

[![Edit 🏁 React Final Form - Simple Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mop6wz3wq8)

**Comment by erikras** [comment]
Ah, yes. The problem is that the DOM only gives string values for inputs. e.g. `typeof event.target.value === 'string'` is always true. You can get around this by adding a
`parse={Number}` prop to all your `Field` components. This will convert the string that the DOM gives back into a `Number` for storage in the JSON. Then the `valueFromState === valueProp` check will work for deciding which radio button should be checked. [Parse docs](https://github.com/final-form/react-final-form#parse-value-any-name-string--any--null).

**Comment by navyfox** [comment]
Thank you. To understand that my problem is in number, I spent 16 hours of my life 😆

**Comment by erikras** [comment]
I think you mean `"16"` hours. 🤣 Glad it's remedied!
