### ISSUE TITLE
Nested values that change identity cause re-initialization

### ISSUE THREAD

**Issue by bobbyrenwick** [final-form/react-final-form#256]
### What is the current behavior?

When you have nested values being passed into initialValues then recreating those initialValues causes a reset of the form back to its original value.

### What is the expected behavior?

That `userStuff.firstName` would still be `"bob"`.

I am experiencing this because I have a large, complicated object that I'm editing in a form that has multiple small editors, each editing a small section of the big object. The current editor that you're looking at is controlled via the URL (hence the recreation with the `editingArea` prop in the example. My `initialValues` is generated from the object stored in an Apollo store, by doing some wrangling in order to get the object into the right shape for the form - hence the `getInitialValues` function in the example.

### Sandbox Link

https://codesandbox.io/s/6zmjz3nz8n

1. Change the first name from `"erikras"` to `"bob"` and see `userStuff.firstName` change to `"bob"`
2. Click the "Other Stuff" button
3. See the `userStuff.firstName` change back to `"erikras"`

### What's your environment?

🏁 React Final Form version: 3.4.2
🏁 Final Form version: 4.6.1 
OS: OS X 10.11.6
Browser: Chrome 66

**Comment by erikras** [comment]
The way to accomplish this is for the container component to keep the combined form state, and then each subform's onSubmit updates the values in the container's state. Like how the [Wizard Example](https://codesandbox.io/s/km2n35kq3v) works.

Also, doing `initialValues={getInitialValues()}` is not a good idea because it's going to be different (`!==`) on every render because you're creating a new object every time.

**Comment by bobbyrenwick** [comment]
Thanks for the response @erikras, I have now stored `initialValues` in state, as you do in the Wizard Example and it's solved my problem, thanks for the suggestion!
