### ISSUE TITLE
"pristine" and "dirty" fail in virtual list form

### ISSUE THREAD

**Issue by Mario-Eis** [final-form/react-final-form#263]
### Are you submitting a **bug report** or a **feature request**?
Bug (I think)

### What is the current behavior?
We chose final form because of its performance when handling large forms. Still, as we use custom components that are a bit slow, we need to virtualize the form for smooth scrolling. Unfortunately there seems to be an issue with that:
When the field scrolls out of view in a virtual list (e.g. react-virtualized), it is unmounted. This seems to break the "pristine" indicator of final form. When the field is in view and gets modified, pristine is false. As soon as the field scrolls out of view and is unmounted, pristine turns true. The form state itself is kept correctly. So if you scroll the field into view again, pristine switches back to false.

### What is the expected behavior?
Pristine should stay valid.

### Sandbox Link
Modify the value of a field. Then scroll up and down.

https://codesandbox.io/s/lpmkpn87o9

### What's your environment?

    "react-final-form": "^3.4.2"
    "final-form": "^4.6.1"

**Comment by erikras** [comment]
Fascinating. I knew it was only a matter of time before someone combined these two technologies. I keep meaning to investigate `react-virtualized` in my own projects.

The issue is that RFF, for reasons that cover more cases than not, calculates `dirty` and `pristine` (and `valid` and `invalid`) based ***only upon the mounted fields***. Virtualized lists are an exception.

What I would recommend is to create a non-rendered list of all the fields. That way they are all registered all the time. Like this:

[![Edit 🏁 React Final Form - Simple Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0m4mvqw7yw)
