### ISSUE TITLE
[Bug?] Placeholders not passed down from field to children input when using render function

### ISSUE THREAD

**Issue by Aduqoum** [final-form/react-final-form#268]
### Are you submitting a **bug report** or a **feature request**?
Bug, I think. it might be how the intentional though

### What is the current behavior?
The place holder field prop are not passed down to the input when using render function to show input

### What is the expected behavior?
The place holder is passed down to the children maybe?
### Sandbox Link
https://codesandbox.io/s/pm5vll9jyx

### What's your environment?
Final form: 4.6.1
React final form: 3.4.0

### Other information
N/A

**Comment by arthurdenner** [comment]
Hi, @Aduqoum. I believe this behaviour is intentional and is correct. If you pass to `Field` a component to render through the `component` prop, it will spread the properties that do not interest `final-form` (such as `placeholder` and `type`. Since you are specifying what will render through the render function, it's up to you to spread the other properties, because `input` contains only what it's interesting to `final-form` (`name`, `value`, `onChange`). So, what you should do is something like the following code:

```javascript
<Field component="input" name="username" placeholder="Username">
  {({ input, meta, ...otherProperties }) => (
    // otherProperties = placeholder, type...
    <div>
      <label>Username</label>
      <input {...input} {...otherProperties} />
      {(meta.error || meta.submitError) &&
        meta.touched && <span>{meta.error || meta.submitError}</span>}
    </div>
  )}
</Field>
```
I hope this explanation makes sense to you, I'm not very good in explaining things. You can also `console.log` the `input` property provided in the render function to see which ones I mean with "contains only what it's interesting to `final-form`."

**Comment by erikras** [comment]
Yes. @arthurdenner nailed it. 👍
