### ISSUE TITLE
Cannot create Field element

### ISSUE THREAD

**Issue by consegrado** [final-form/react-final-form#318]
### Are you submitting a bug report or a feature request?
Bug report

### What is the current behavior?

`<Field name="cardNumber" placeholder="Номер карты" component="input" type="text" />`

Cannot create `Field` element because in property `component`:
 - Either string [1] is incompatible with `React.StatelessFunctionalComponent` [2].
 - Or string [1] is incompatible with statics of `React.Component` [3].

### What is the expected behavior?
No warnings

### What's your environment?
🏁 React Final Form version 3.6.5
🏁 Final Form version 4.9.1
Flow 0.79.1

**Comment by erikras** [comment]
Sandbox? I'm not fully understanding the problem.

**Comment by consegrado** [comment]
https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0uLc4Ce6lUAGUAruky5KAEwCSAO3QicZALytkCpS1AAfViUrRKnXaxyUAHjiLsiXbpYl4+A0ADFkhqVTlTKWAAVGdFVQAG9EUFANRRwALnDIqNA5IlRKBJIcLA0AcwAaJKiANyJoEQziOV5C5NAaAAtjAGtpAH4EgCNYWCMiOSSAX1rQdOsEiLqQUAAVAHkAETmEgFkiVuJQKWRISFBYPYADDy8ha3ND0HhkHAbYJWJoaFBbwUgROTpkWDkSIuIvsVKB1QN1etQ5CMolIiNYQXNOgArYw4KFbZC4XggsF9SH-baYoQaGiUAAypBwok6qBu2J6uLR-kYWBB-Rq-w0N2QZTp4P6aI0pWgyCkvIZ-3QOSyGmBXXpELRJBE1JuAFEsMzWdVFcqaTg3ERkEZRXK+Xi6kqVZSRDQSdJ2qbxXUcPdGg7QfL+f8hSKxQrvcgSDd3TiIUNEIMHBYnC9+IIfH4sEROkYgrAQgAeGYAPlAakm9SYmDklDkOBBVFoOAAdABhIs-Us4GZxjP4bMjRpGqTsOQggAU-cl6ZICRmAEo87nK3RqwA5WB+Sd6Gc1hd+Ea9xMD4chMeTlTTjhrxeUCNRmMuQQnaBSNMhPOJKJlODwOciJ5+r1RSDYVCwgchQqBI2XyFI0kqLIcjkXID1zUCkl-LB-xwOY5AAIXKFlHX9KJA1VABHEQeQSfsiBA7VQQo3g4I9M0RlSdJMmyPIRnQGwDEAspgKqGpwKY0AoLyWiEJKMoRVhSgbykEgQSEmCAG0AF0RiA2VeIjUAADIKFLRNk1TYISAzaSE38e8SFzHSCxoBsSzLCtjzrOymxbAQ21zPRRHEbBzFkTRlHPbhuD8GhoBsQRHF80BSiwdxPFvBJV2cjBGzLNzKBMhK7yM7NuCiRAsq8fjKBUAAiGgbCkd9UE6fwytAdBwpJO5b38crAFwQQA+EEAHhBAFYQQABEFAQAuEEABhABsAIRBAGkQBrbNS+ycHKmIlAaq9yvMKwGuAPKkiSIA

**Comment by noashka** [comment]
Same error http://prntscr.com/kwog3z
flow: 0.2.3

**Comment by hallettj** [comment]
This is due to a conflict in the [Flow type definitions](https://github.com/final-form/react-final-form/blob/master/src/types.js.flow#L92). This is an excerpt from the `FieldProps` type:

```js
& RenderableProps<FieldRenderProps> & {
    component?: React.ComponentType<*> | SupportedInputs
}
```

The type for the `component` field that you see there is correct because `SupportedInputs` is a union of the string types `'input'`, `'select'`, and `'textarea'`. But `RenderableProps` declares a more restrictive type for the `component` prop:

```js
export type RenderableProps<T> = {
  component?: React.ComponentType<*>,
  children?: ((props: T) => React.Node) | React.Node,
  render?: (props: T) => React.Node
}
```

Because these types are in a union the most restrictive type takes precedence. Effectively this disallows string values for the `component` prop.

This could perhaps be fixed by changing the type for `component` in `RenderableProps` from `React.ComponentType<*>` to `React.ElementType`.
