### ISSUE TITLE
[BUG] FormStateToRedux - Maximum update depth exceeded

### ISSUE THREAD

**Issue by borm** [final-form/react-final-form#335]
All forms with initial values

### No nested input names
Original simple example  - [codesandbox](https://codesandbox.io/s/vvn8y2m7y7)
Original example with connected **Container**  - [codesandbox](https://codesandbox.io/s/vvn8y2m7y7)

### Nested input names
_Bug_
Original example with connected **Container** and nested **initialValues** & **input names**  - [codesandbox](https://codesandbox.io/s/1o2rn6yo7)

_Fix_
Original example with connected **Container** & **Form** and nested **initialValues** & **input names**  - [codesandbox](https://codesandbox.io/s/0om2xrolrl)

**Comment by erikras** [comment]
I'm sorry, but I'm not seeing that error when typing in the fields. Can you give me some steps to reproduce?

**Comment by borm** [comment]
update code

**Comment by borm** [comment]
fuck, something wrong in my example

**Comment by borm** [comment]
updated again

**Comment by erikras** [comment]
Ooh!!! This was an interesting one!!

The `Form` component is only doing a _shallow_ equals check on the `initialValues` prop to determine if it has changed. If it _has_ changed, then it reinitializes the form, which, in turn, was dispatching the update action via the `FormSpy`. That's why it works if the `initialValues` are flat, but not if they are deep.

I think that it probably needs to do a _deep_ equals check on `initialValues`, but for now you can work around it by not creating a new object of your `initialValues` every time the connected component rerenders. See lines 20-25:

[![Edit 🏁 React Final Form - Redux Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ozrvvpjnq)

Personally, I would _not_ connect the container of the form to Redux in this way; I would only connect whatever particular deeper component needs that state. Makes sense?

**Comment by borm** [comment]
Oh, my initialValues depended from BackEnd, it`s cant be static

**Comment by erikras** [comment]
That's fine, as long as it's the same object coming from Redux or whatever is loading them. You just can't _construct_ a new object when passing the prop.

That said, I will implement deep equals on the `initialValues` check.

**Comment by borm** [comment]
So in my case I have something like Wizard, but I have several forms that follow the previous one

For example on one page

Form1 - submited, rendered
Form2 - not submited, rendered
Form3 - not rendered, waiting for submit Form2 to render

And i need set disabled for next form when any previously is changed

**Comment by borm** [comment]
as example i can define  initial values  in component constructor, makes sense?

**Comment by erikras** [comment]
Yep. As long as the object is only instantiated when they actually change, you should be fine.

**Comment by borm** [comment]
when you planned fix it?

**Comment by erikras** [comment]
Yes, sorry. This week has been busy.

**Comment by erikras** [comment]
Okay, so `deepEqual()` is complicated. I wonder if we could allow an `isEqual` function to be passed in for `initialValues` checking....

**Comment by arthurdenner** [comment]
@erikras would you consider using [react-fast-compare](https://github.com/FormidableLabs/react-fast-compare) to compare `initialValues`? Seems like a good alternative to solve the problem and it's pretty small too.

**Comment by erikras** [comment]
Published fix in [`v3.6.6`](https://github.com/final-form/react-final-form/releases/tag/v3.6.6).

**Comment by erikras** [comment]
@arthurdenner My reasoning on going with a function prop is that most people won't need it, as most forms are not deeply structured, but to allow flexibility for those that are.

**Comment by arthurdenner** [comment]
@erikras Got it. Thanks for explaining it.
