### ISSUE TITLE
re-introduce withReactFinalForm HOC?

### ISSUE THREAD

**Issue by onlyann** [final-form/react-final-form#480]
### Are you submitting a **bug report** or a **feature request**?

Feature Request

`withReactFinalForm` HOC has been removed in v5.
I understand that it is probably to keep the package as small as possible now that React Final Form has moved to Hooks.

Maybe you would consider it okay to re-introduce it for 2 reasons :
- an application that hasn't yet moved to hooks wouldn't be able to use `useForm` within a class component.
- less likely to cause a breaking change when moving from v4 to v5.

If it makes more sense to be done in user land, then should we update the documentation to include the trivial bit of code needed to implement `withReactFinalForm` ?

**Comment by erikras** [comment]
I'm not sure what "hasn't yet moved to hooks" means. If you aren't using React 16.8+, you can't use RFFv5, because it uses hooks internally.

Until you can upgrade React, RFFv4 works just fine. The functionality is effectively the same between RFFv4 and RFFv5 (although one minor feature was added in `v5.1`).

[HOCs were never intended to be a part of this library](https://github.com/final-form/react-final-form/blob/master/docs/faq.md#why-no-hoc). `withReactFinalForm` was introduced to accommodate the new context API, and I think don't think it was a great decision to export it.

If you really need it, it's a one liner to write your own. This is why React is so awesome.
```jsx
const withReactFinalForm = Component => props =>
  <Component reactFinalForm={useForm()} {...props} /> 
```
I've pasted this into the release notes. Great suggestion!

I think supplying a bunch of one line utility functions is not good library API design, because people come to rely on them, and it is more to maintain and possibly break. That's why much of the awesome stuff you can do with this library are demonstrated with custom components in the Examples, meant to be copied and pasted rather than installed from npm.

**Comment by onlyann** [comment]
No worries. Thanks for this great library 🙏🏻
