### ISSUE TITLE
Undocumented format/formatOnBlur behavior change between v4 and v5/6

### ISSUE THREAD

**Issue by ThiefMaster** [final-form/react-final-form#514]
When updating from v4 to v6, I noticed some `undefined` values being passed by my inputs. This happened consistently when the field was empty and had `formatOnBlur` or a custom `format` function set.

I believe this is because v4 had this code:

https://github.com/final-form/react-final-form/blob/v4.1.0/src/Field.js#L199-L203

Not sure what the point of always calling the *default* formatter (undefined to empty string) regardless of the configured formatter is (a bug?), but whatever the reason, it ensured no `undefined` was passed to the field (which was great - who wants uncontrolled fields inside a form after all?).

Anyway, with the rewrite this code is now gone, and thus I now need to adapt my custom formatters to convert undefined properly. No big deal, but having this documented would be great - it took me quite some time to figure out why I suddenly had undefined values after updating.

**Comment by ThiefMaster** [comment]
Looks like v6 has something similar here:

https://github.com/final-form/react-final-form/blob/master/src/useField.js#L180-L186

But it's gated behind a `component === 'input'` check, which breaks my usecase where *all* fields use a custom adapter component (to take care of showing errors nicely etc.). From what I see there is currently no way to keep the undefined-to-empty-string conversion during the first render (before doing anything with the field)

**Comment by ThiefMaster** [comment]
Any update on this one? It's blocking me from updating and it'd be good to know if this was an intentional change / I'm doing something wrong, or if this was unintentional and will be fixed.

**Comment by erikras** [comment]
Hmm.. [It seems pretty intentional](https://github.com/final-form/react-final-form/blob/master/src/Field.test.js#L316-L333), but I cannot recall my reasoning behind choosing to only use the `defaultFormat` for `input` elements. But let me think for a moment to try and guess at Past @erikras's motivations... 🤔

...

Over the years, library consumers seem pretty split on whether or not they expect an `undefined` value to actually be delivered to the component as `undefined` or not. The `<Field component="input"/>` structure has always been primarily for "let's get something off the ground" step of form development; i.e. I think that any large, mature application using this library is probably going to have their own custom input components, and will very rarely actually use `component="input"` in production. As such, I think it's a little bit more _honest_ of the form library to represent `undefined` as `undefined` rather than do the `value || ''` hack designed _only_ to get around React's ["any input given a value of `undefined` is 'uncontrolled'"](https://reactjs.org/docs/forms.html#controlled-input-null-value) rule.

So I think that, despite the extra work it's going to cost you at the moment, I've re-convinced myself that this is a _better_ way to do things, and that this change should stay as is.

Does my reasoning make sense to you?

**Comment by ThiefMaster** [comment]
OK, fair enough. I think I managed to solve it like this: https://github.com/indico/indico/pull/3981/files#diff-33b9380ef61fc064e580c263fae633a5R76
