### ISSUE TITLE
checked radiobutton default pristine 

### ISSUE THREAD

**Issue by Gi972** [final-form/react-final-form#57]
### Are you submitting a **bug report** or a **feature request**?
Maybe a bug or just a example with radio button and pristine and value.

### What is the current behavior?
I want a example with a checked radiobutton because, I want submit my form only if a data change but when I try it in the simple example I added checked="true" on the Field. I don't have the value curly properties (in JSON.stringify(values, 0, 2)  in the value but a empty object.   

You can look at:
https://codesandbox.io/s/71p6o782j6

Thanks

**Comment by erikras** [comment]
Great question. This is a common source of confusion. 👍

For that, you must specify an initial value. For example, look at the checkbox in that example. If it wasn't initialized, then, once it's clicked it would only ever be `true` or `false`, and never `undefined`, so it will never get back to pristine. Radio buttons, when properly designed, are the same way. That was an oversight of mine in making that example.

Does that make sense?

**Comment by Gi972** [comment]
Thanks for your explanation @erikras 

I had not seen the initialvalue properties   ^_^'

Thanks again.

**Comment by pantchox** [comment]
Hi @erikras 
From the classic simple example i found that pristine does not work on multiple checkboxes

https://codesandbox.io/s/xjw9r381wp

in this example i added to initialValue object empty `sauces` array.
When i check and then uncheck it returns to initial values, but the submit button returns to be non disabled.

is this intentional or a bug?

Also if this is a bug, in the docs it says pristine does shallow compare.
Meaning that is the initial values of  `sauces` array was 2 selections, playing with the checkbox can select them both in a diffrent order in the array.
that should also make pristine set as true (?)

thanks.
