### ISSUE TITLE
why value is not set in dropdown in form using react?

### ISSUE THREAD

**Issue by naveennsit** [final-form/react-final-form#601]
I am setting the initial value in dropdown using final-form with semantic ui react .it is not reflecting why ?

Here is my code
https://codesandbox.io/s/awesome-golick-hghg9
initialValues={{ ag: "ax" }}
{ key: "ax", value: "ax", text: "Aland Islands" },

Expected output is Aland Istand should display when application run

**Comment by naveennsit** [comment]
I am setting the initial value in dropdown using final-form with semantic ui react .it is not reflecting why ?

Here is my code
https://codesandbox.io/s/awesome-golick-hghg9
initialValues={{ ag: "ax" }}
{ key: "ax", value: "ax", text: "Aland Islands" },

Expected output is Aland Istand should display when application run

**Comment by CodeWithOz** [comment]
@naveennsit hmm it seems there may be a number of things you're not doing right. The main problem is in `example.js` where you have `value={val}` as a prop of `<Dropdown />`. Final Form provides the value of the field in `props.input.value`, so in your sandbox example, you should have `value={input.value}` instead of `value={val}`. Therefore, there's no need to destructure `val` from the `props` object (if you `console.log(val)` you'll see that it's `undefined`).

This brings us to the next point which is that you are spreading `props.input` into `<Dropdown />`. As I've just mentioned, `props.input` contains the field's value in a `value` key, so by spreading `props.input`, you have already provided the correct value to `<Dropdown />` and there's no need to try to pass in the same value as an individual prop.

The next problem is that you're using both the `defaultValue` and `value` props of `<Dropdown />`, which throws a warning in the console saying that you should only use one or the other but not both at the same time. Spreading `props.input` guarantees that `<Dropdown />` will always get a `value` prop, so passing something for `defaultValue` will always cause this warning.

Here's an [adjusted sandbox](https://codesandbox.io/s/crimson-wood-pbei7) showing these changes. I've removed the lines where you passed both `defaultValue` and `value`, and as you can see, the form field is showing the correct initial value.
