### ISSUE TITLE
Are all values in final-form string ? or Is it possible to have Int and other types too ?

### ISSUE THREAD

**Issue by kavink** [final-form/react-final-form#62]
I want a fields values to be integer. But when I try TextField from material ui, with `type="number"`

The value in form still is a string. Any thoughts if only string can be saved as values in form or int/json etc can also be saved ?

**Comment by erikras** [comment]
Final Form values can be `any`. It's up to whoever is calling `onChange` to call it with the right type.

I will caution you, however, to avoid `Number` values on controlled inputs that you type into. The reason is that your decimal point will always be erased. If you type `3.`, a controlled input will immediately rerender with `3`, so you can never type a number with decimals character by character. This is _probably_ why MUI is giving you a string.
