### ISSUE TITLE
Field.format return Typescript type should be considered for Field.component

### ISSUE THREAD

**Issue by htulipe** [final-form/react-final-form#918]
### What is the current behavior?

I have a custom input that requires it's value in a certain shape (an object with an "url" key). My form uses this custom input to render a simple string. The "reconciliation" is done in the Field.format function where I take the form's string and return an object with the "url" key:

```
<Field
    name="image"
    format={(v) => ({ url: v })}
    component={CustomInput}
/>
```

Here I have no issue but "v" is of type any. My problem occurs when I want to have a bit of type safety:

```
interface FormValues {
   image: string
}

<Field<FormValues["image"]> 
   ...
 />
```

This types "v" args as a string (which is fine) but cause a TS error on the component prop:

```
Type 'string' is not assignable to type '{ url: string; }'.
```

### What is the expected behavior?

I would expect no error since CustomInput will always receive a valid value thanks to my format function

### Sandbox Link

https://codesandbox.io/s/infallible-cookies-i7t3p

### What's your environment?

final-form@4.20.2
react-final-form@6.5.3
node v14.15.1

**Comment by tjb042** [comment]
The typescript error you're receiving here is because of a type mismatch between what the FieldValue type is explicitly set to (string) and the CustomInput's type declaration ({ url: string }.

I'm assuming here that you want the form state to have an image property of string, while still passing in the complex object to the CustomInput. In that case, I believe, you need to change the FieldValue type to match the CustomInput's type and implement a parse function to convert the object returned from the CustomInput back into a string that can be stored in the form. Note that the format prop is almost always used in conjunction with the parse prop, especially when doing type conversion.

```
// Creating a simple interface to demonstate the point
// This represents the type of object the custom input requires
interface CustomInputType {
  url: string,
}

// This represents the shape the form values must take
// notice that string is incompatible with CustomInputType which is what Typescript complained about
interface FormValues {
  image: string;
}
```

So later in your JSX is where the magic happens....
```
// we use format to convert from string (FormValues.image) to CustomInputType
// we use parse to convert from CustomInputType back into string to be stored in the form
// notice the Field's FieldType is CustomInputType _not_ string
<Field<CustomInputType>
      name="image"
      format={(v) => ({ url: v })}
      parse={(v) => v.url}
      component={CustomInput}
/>
```

**Comment by htulipe** [comment]
Thanks for your answer @tjb042 it works indeed though I find a bit odd to use CustomInputType for the field value.
